spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  profiles:
    active: dev
file:
  upload-dir: ${UPLOAD_DIR}

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 9000000
  clientOrigin: ${CLIENT_ORIGIN}

logging:
  level:
    org:
      hibernate:
        sql: DEBUG

